import {
  LayoutDashboard,
  Users,
  Building2,
  DollarSign,
  FileText,
  Handshake,
  UserCheck,
  CreditCard,
  Receipt,
  Settings,
  TrendingUp,
  FolderOpen,
  BookOpen,
  Target,
  Globe,
} from 'lucide-react';
import type { RoleMenuConfig } from '@/types';

export const ROLE_MENU_CONFIG: RoleMenuConfig[] = [
  {
    roleName: 'Counselor',
    roleIdValue: 'aab9d855-52f9-fc84-fcf7-5bcef0c27d31',
    menuItems: [
      {
        id: 'counselor-dashboard',
        label: 'My Dashboard',
        href: '/counselor/dashboard',
        icon: LayoutDashboard,
        requiredParams: { role: '{roleId}', counselor_name: '{fullname}' },
      },
      {
        id: 'counselor-leads',
        label: 'My Leads',
        href: '/counselor/leads',
        icon: Target,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'counselor-students',
        label: 'My Students',
        href: '/counselor/students',
        icon: Users,
        requiredParams: { role: '{roleId}', actionfrom: 'sidebar' },
      },
      {
        id: 'counselor-students-new',
        label: 'My Students New',
        href: '/counselor/students-new',
        icon: UserCheck,
        requiredParams: { role: '{roleId}', actionfrom: 'sidebar' },
      },
      {
        id: 'counselor-programs',
        label: 'My Programs',
        href: '/counselor/programs',
        icon: BookOpen,
        requiredParams: { role: '{roleId}', actionfrom: 'sidebar' },
      },
      {
        id: 'counselor-subagents',
        label: 'SubAgents',
        href: '/counselor/subagents',
        icon: Handshake,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
  {
    roleName: 'Admission Officer',
    roleIdValue: '76e53207-38c4-b9cd-a348-5bcef1cb6535',
    menuItems: [
      {
        id: 'ao-dashboard',
        label: 'My Dashboard',
        href: '/ao/dashboard',
        icon: LayoutDashboard,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ao-leads',
        label: 'My Leads',
        href: '/ao/leads',
        icon: Target,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ao-all-students',
        label: 'All Students',
        href: '/ao/all-students',
        icon: Users,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ao-students-new',
        label: 'My Students New',
        href: '/ao/students-new',
        icon: UserCheck,
        requiredParams: { role: '{roleId}', actionfrom: 'sidebar' },
      },
      {
        id: 'ao-programs',
        label: 'All Programs',
        href: '/ao/programs',
        icon: BookOpen,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ao-subagents',
        label: 'SubAgents',
        href: '/ao/subagents',
        icon: Handshake,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ao-documents',
        label: 'Institute Documents',
        href: '/ao/documents',
        icon: FileText,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
  {
    roleName: 'Branch Manager',
    roleIdValue: '6728565b-ceae-908c-3c9c-5bceeffe0236',
    menuItems: [
      {
        id: 'bm-performance',
        label: 'Performance',
        icon: TrendingUp,
        children: [
          {
            id: 'bm-office-performance',
            label: 'My Office Performance',
            href: '/bm/office-performance',
            requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
          },
          {
            id: 'bm-counselors-performance',
            label: 'My Counselors Performance',
            href: '/bm/counselors-performance',
            requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
          },
          {
            id: 'bm-collection-report',
            label: 'Collection Report',
            href: '/bm/collection-report',
            requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
          },
        ],
      },
      {
        id: 'bm-dashboard',
        label: 'Dashboard',
        icon: LayoutDashboard,
        children: [
          {
            id: 'bm-counselors-dashboard',
            label: 'My Counselors Dashboard',
            href: '/bm/counselors-dashboard',
            requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
          },
        ],
      },
      {
        id: 'bm-finance',
        label: 'Finance',
        icon: DollarSign,
        children: [
          {
            id: 'bm-office-expenses',
            label: 'Office Expenses',
            href: '/bm/office-expenses',
            requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
          },
        ],
      },
      {
        id: 'bm-office-leads',
        label: 'My Office Leads',
        href: '/bm/office-leads',
        icon: Target,
        requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
      },
      {
        id: 'bm-office-students',
        label: 'My Office Students',
        href: '/bm/office-students',
        icon: Users,
        requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
      },
      {
        id: 'bm-office-students-new',
        label: 'Office Students New',
        href: '/bm/office-students-new',
        icon: UserCheck,
        requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
      },
      {
        id: 'bm-office-programs',
        label: 'My Office Programs',
        href: '/bm/office-programs',
        icon: BookOpen,
        requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
      },
      {
        id: 'bm-institute-documents',
        label: 'Institute Documents',
        href: '/bm/institute-documents',
        icon: FileText,
        requiredParams: { role: '{roleId}', branch_id: '{branchId}' },
      },
    ],
  },
  {
    roleName: 'CEO',
    roleIdValue: '5f3f04eb-dd12-7cde-7e33-5ec7f4cddb07',
    menuItems: [
      {
        id: 'ceo-dashboards',
        label: 'Dashboards',
        icon: LayoutDashboard,
        children: [
          {
            id: 'ceo-dashboard',
            label: 'CEO Dashboard',
            href: '/ceo/dashboard',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-finance-dashboard',
            label: 'Finance Dashboard',
            href: '/ceo/finance-dashboard',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-counselor-dashboard',
            label: 'Counselor Dashboard',
            href: '/ceo/counselor-dashboard',
            requiredParams: { role: '{roleId}' },
          },
        ],
      },
      {
        id: 'ceo-subagents',
        label: 'SubAgents',
        icon: Handshake,
        children: [
          {
            id: 'ceo-subagent-control',
            label: 'SubAgent Control Room',
            href: '/ceo/subagent-control',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-all-subagents',
            label: 'All SubAgents',
            href: '/ceo/all-subagents',
            requiredParams: { role: '{roleId}' },
          },
        ],
      },
      {
        id: 'ceo-revenue',
        label: 'Revenue & Expenses',
        icon: DollarSign,
        children: [
          {
            id: 'ceo-exp-definitions',
            label: 'Exp. Definitions',
            href: '/ceo/exp-definitions',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-expenses-list',
            label: 'Expenses List',
            href: '/ceo/expenses-list',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-pl-by-office',
            label: 'Profit & Loss By Office',
            href: '/ceo/pl-by-office',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-counselor-bonuses',
            label: 'Counselors Bonuses',
            href: '/ceo/counselor-bonuses',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-collection-report',
            label: 'Collection Report',
            href: '/ceo/collection-report',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-expenses-report',
            label: 'Expenses Report',
            href: '/ceo/expenses-report',
            requiredParams: { role: '{roleId}' },
          },
        ],
      },
      {
        id: 'ceo-performance',
        label: 'Performance',
        icon: TrendingUp,
        children: [
          {
            id: 'ceo-institute-performance',
            label: 'Institute Performance',
            href: '/ceo/institute-performance',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-office-performance',
            label: 'Office Performance',
            href: '/ceo/office-performance',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-counselor-performance',
            label: 'Counselor Performance',
            href: '/ceo/counselor-performance',
            requiredParams: { role: '{roleId}' },
          },
        ],
      },
      {
        id: 'ceo-misc',
        label: 'Misc',
        icon: Settings,
        children: [
          {
            id: 'ceo-staff-card',
            label: 'Staff Directory Card View',
            href: '/ceo/staff-card',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-staff-table',
            label: 'Staff Directory Table View',
            href: '/ceo/staff-table',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-ao-workload',
            label: 'AO Work Load',
            href: '/ceo/ao-workload',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-course-stats',
            label: 'Course Provider Stats',
            href: '/ceo/course-stats',
            requiredParams: { role: '{roleId}' },
          },
          {
            id: 'ceo-scholarships',
            label: 'Scholarships',
            href: '/ceo/scholarships',
            requiredParams: { role: '{roleId}' },
          },
        ],
      },
      {
        id: 'ceo-all-students',
        label: 'All Students',
        href: '/ceo/all-students',
        icon: Users,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ceo-students-new',
        label: 'My Students New',
        href: '/ceo/students-new',
        icon: UserCheck,
        requiredParams: { role: '{roleId}', actionfrom: 'sidebar' },
      },
      {
        id: 'ceo-all-programs',
        label: 'All Programs',
        href: '/ceo/all-programs',
        icon: BookOpen,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ceo-all-leads',
        label: 'All Leads',
        href: '/ceo/all-leads',
        icon: Target,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ceo-leads-assignment',
        label: 'Leads Assignment',
        href: '/ceo/leads-assignment',
        icon: UserCheck,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ceo-assignment-dashboard',
        label: 'Assignment Dashboard',
        href: '/ceo/assignment-dashboard',
        icon: LayoutDashboard,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ceo-agreements',
        label: 'IGECAgreements',
        href: '/ceo/agreements',
        icon: FileText,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'ceo-institute-documents',
        label: 'Institute Documents',
        href: '/ceo/institute-documents',
        icon: FolderOpen,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
  {
    roleName: 'Sponsor',
    roleIdValue: '819889c0-5cfc-75ee-9233-6737158c0c0c',
    menuItems: [
      {
        id: 'sponsor-dashboard',
        label: 'My Dashboard',
        href: '/sponsor/dashboard',
        icon: LayoutDashboard,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'sponsor-students',
        label: 'My Students',
        href: '/sponsor/students',
        icon: Users,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'sponsor-students-new',
        label: 'My Students New',
        href: '/sponsor/students-new',
        icon: UserCheck,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'sponsor-export',
        label: 'Export Students List',
        href: '/sponsor/export',
        icon: FileText,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'sponsor-documents',
        label: 'Institute Documents',
        href: '/sponsor/documents',
        icon: FolderOpen,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
  {
    roleName: 'Business Unit Manager',
    roleIdValue: '8db073a8-7d57-b887-2885-676e2d053019',
    menuItems: [
      {
        id: 'bum-dashboard',
        label: 'My Dashboard',
        href: '/bum/dashboard',
        icon: LayoutDashboard,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'bum-institute-performance',
        label: 'Institute Performance',
        href: '/bum/institute-performance',
        icon: TrendingUp,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'bum-all-institutes',
        label: 'All Institutes Data',
        href: '/bum/all-institutes',
        icon: Building2,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
  {
    roleName: 'Collection Manager',
    roleIdValue: 'collection-manager-placeholder',
    menuItems: [
      {
        id: 'cm-dashboard',
        label: 'Dashboard',
        href: '/cm/dashboard',
        icon: LayoutDashboard,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'cm-all-students',
        label: 'All Students',
        href: '/cm/all-students',
        icon: Users,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'cm-invoicing',
        label: 'Ready for Invoicing Programs',
        href: '/cm/invoicing',
        icon: Receipt,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'cm-receivable',
        label: 'Receivable Invoices',
        href: '/cm/receivable',
        icon: CreditCard,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'cm-collected',
        label: 'Collected Invoices',
        href: '/cm/collected',
        icon: DollarSign,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'cm-subagent-invoices',
        label: 'Subagent Invoices',
        href: '/cm/subagent-invoices',
        icon: Handshake,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
  {
    roleName: 'Global Users',
    roleIdValue: 'global-users-placeholder',
    menuItems: [
      {
        id: 'gu-dashboard',
        label: 'Global Users Dashboard',
        href: '/gu/dashboard',
        icon: Globe,
        requiredParams: { role: '{roleId}' },
      },
      {
        id: 'gu-all-students',
        label: 'All Students',
        href: '/gu/all-students',
        icon: Users,
        requiredParams: { role: '{roleId}' },
      },
    ],
  },
];

export const getMenuConfigForRole = (roleName: string): RoleMenuConfig | undefined => {
  return ROLE_MENU_CONFIG.find((config) => config.roleName === roleName);
};

export const getAllRoleNames = (): string[] => {
  return ROLE_MENU_CONFIG.map((config) => config.roleName);
};
